name: tienda1_app
description: Just another tienda1 app
version: 1.0.0+1
publish_to: none


environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  core: ^0.1.0+1
  ui_system: ^0.1.0+1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

